name: Master Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 8
        java-package: jdk
        architecture: x64
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Run build
      run: ./gradlew build 

    - name: Update coveralls coverage report
      run: ./gradlew coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
