name: Publish release artifacts

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        java-package: jdk
        architecture: x64

    - name: Build artifacts
      run: ./gradlew clean build -x test -x check


    - name: Publish to Bintray
      run: ./gradlew bintrayUpload
      env:
        BINTRAY_USER: ${{ github.actor }}
        BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
